version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ecoflow_db
    restart: always
    environment:
      POSTGRES_USER: ecoflow
      POSTGRES_PASSWORD: ecoflow_password
      POSTGRES_DB: ecoflow_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecoflow_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://ecoflow:ecoflow_password@db:5432/ecoflow_db?schema=public
      - JWT_SECRET=ecoflow_super_secret_jwt_key
      - PORT=3000
    depends_on:
      - db

volumes:
  pgdata:
